apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - ./presidio-pvc.yaml
  - ./helm/out/presidio/templates/analyzer-deployment.yaml
  - ./helm/out/presidio/templates/anonymizer-deployment.yaml
  - ./helm/out/presidio/templates/analyzer-service.yaml
  - ./helm/out/presidio/templates/anonymizer-service.yaml
  - ./helm/out/presidio/templates/analyzer-ingress.yaml
namespace: presidio
