---
# Source: presidio/templates/analyzer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-presidio-analyzer
  labels:
    app: presidio-presidio-analyzer
    chart: "presidio-2"
    release: "presidio"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presidio-presidio-analyzer
  template:
    metadata:
      labels:
        app: presidio-presidio-analyzer
    spec:
      containers:
      - name: presidio
        image: "ghcr.io/presidio-analyzer:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 1500Mi
            cpu: 1500m
          limits:
            memory: 3000Mi
            cpu: 2000m
        env:
          - name: PORT
            value: "8080"
