---
# Source: presidio/templates/anonymizer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-presidio-anonymizer
  labels:
    app: presidio-presidio-anonymizer
    chart: "presidio-2"
    release: "presidio"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presidio-presidio-anonymizer
  template:
    metadata:
      labels:
        app: presidio-presidio-anonymizer
    spec:
      containers:
      - name: presidio
        image: "ghcr.io/presidio-anonymizer:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 128Mi
            cpu: 125m
          limits:
            memory: 512Mi
            cpu: 500m
        env:
          - name: PORT
            value: "8080"
