apiVersion: v2
name: deid-presidio
description: A Helm chart for deploying Presidio with swiss-specific ConfigMaps and values
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - presidio
  - deid
  - privacy
  - helm
maintainers:
  - name: vancauwe
  - name: cmdoret
sources:
  - https://github.com/sdsc-ordes/deid-module
