{{ $fullname := include "presidio.analyzer.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-recognizers"
data:
  default-analyzer.yaml:
    |-
      {{ .Files.Get "conf/presidio-analyzer/default-recognizers.yaml" | indent 2 }}
