{{ $fullname := include "presidio.analyzer.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-recognizers-config"
data:
  default-recognizers.yaml: |-
{{ .Files.Get "conf/default-recognizers.yaml" | indent 4 }}
