{{ $fullname := include "presidio.analyzer.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-analyzer-config"
data:
  default-analyzer.yaml: |-
{{ .Files.Get "conf/default-analyzer.yaml" | indent 4 }}
