{{ $fullname := include "presidio.analyzer.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-config"
data:
  default-analyzer.yaml: |-
    {{ .Files.Get "../conf/presidio-analyzer/default-analyzer.yaml" | indent 2 }}
